package rw.okila.sm.model;
// Generated Jun 2, 2022 1:14:30 PM by Hibernate Tools 4.3.1



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private String tinnumber;
     private String firstname;
     private String lastname;
     private String phonenumber;
     private String email;
     private String address;
     private String type;

    public Customers() {
    }

	
    public Customers(String tinnumber) {
        this.tinnumber = tinnumber;
    }
    public Customers(String tinnumber, String firstname, String lastname, String phonenumber, String email, String address, String type) {
       this.tinnumber = tinnumber;
       this.firstname = firstname;
       this.lastname = lastname;
       this.phonenumber = phonenumber;
       this.email = email;
       this.address = address;
       this.type = type;
    }
   
    public String getTinnumber() {
        return this.tinnumber;
    }
    
    public void setTinnumber(String tinnumber) {
        this.tinnumber = tinnumber;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getPhonenumber() {
        return this.phonenumber;
    }
    
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


