package rw.okila.sm.model;
// Generated Jun 2, 2022 1:14:30 PM by Hibernate Tools 4.3.1



/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private String prodtin;
     private String prodname;
     private String proddescription;
     private String prodtype;
     private String mandate;
     private String expdate;
     private String price;

    public Products() {
    }

	
    public Products(String prodtin) {
        this.prodtin = prodtin;
    }
    public Products(String prodtin, String prodname, String proddescription, String prodtype, String mandate, String expdate, String price) {
       this.prodtin = prodtin;
       this.prodname = prodname;
       this.proddescription = proddescription;
       this.prodtype = prodtype;
       this.mandate = mandate;
       this.expdate = expdate;
       this.price = price;
    }
   
    public String getProdtin() {
        return this.prodtin;
    }
    
    public void setProdtin(String prodtin) {
        this.prodtin = prodtin;
    }
    public String getProdname() {
        return this.prodname;
    }
    
    public void setProdname(String prodname) {
        this.prodname = prodname;
    }
    public String getProddescription() {
        return this.proddescription;
    }
    
    public void setProddescription(String proddescription) {
        this.proddescription = proddescription;
    }
    public String getProdtype() {
        return this.prodtype;
    }
    
    public void setProdtype(String prodtype) {
        this.prodtype = prodtype;
    }
    public String getMandate() {
        return this.mandate;
    }
    
    public void setMandate(String mandate) {
        this.mandate = mandate;
    }
    public String getExpdate() {
        return this.expdate;
    }
    
    public void setExpdate(String expdate) {
        this.expdate = expdate;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


